# distribution
dist: xenial
# language
language: python
python:
  - "3.7"
# test environments
env:
  global:
    - PYMOL_PREFIX=/opt/pymol
    - PYMOL_MODULES=/opt/pymol/modules
    - PYTHONPATH=$PYMOL_MODULES
  matrix:
    #For PyMOL 1.8, GROMACS 2018
    - PYMOL_VER=1.8 PYMOL_PACKAGE=travisci-pymol-18 GROMACS_VER=2018.3 GROMACS_PACKAGE=travisci-gromacs-2018
# add ppa
matrix:
  include:
    env: PYMOL_VER=1.8 PYMOL_PACKAGE=travisci-pymol-18 GROMACS_VER=2018.3 GROMACS_PACKAGE=travisci-gromacs-2018
    addons:
      apt:
        sources:
          - sourceline: 'ppa:makson96/dynamics'
        packages:
        - travisci-pdb-files
        - travisci-pymol-18
        - travisci-gromacs-2018
install:
  - pip install -r tests/requirements.txt
# command to run tests
script:
  - bash tests/run.sh
